export const AUTH_AUDIT_EVENTS = {
  REGISTERED: 'AUTH_REGISTERED',
  LOGIN_SUCCEEDED: 'AUTH_LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  LOGOUT: 'AUTH_LOGOUT',
  LOGOUT_ALL: 'AUTH_LOGOUT_ALL',
  PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'AUTH_PASSWORD_RESET_COMPLETED',
  EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  EMAIL_VERIFICATION_RESENT: 'AUTH_EMAIL_VERIFICATION_RESENT',
  SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  ROLE_CHANGED: 'AUTH_ROLE_CHANGED',
  REFRESH_SUCCEEDED: 'AUTH_REFRESH_SUCCEEDED',
  REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  CLUB_SETTINGS_UPDATED: 'CLUB_SETTINGS_UPDATED'
} as const;

export type AuthAuditEvent = (typeof AUTH_AUDIT_EVENTS)[keyof typeof AUTH_AUDIT_EVENTS];
